version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies
    groups:
      development-dependencies:
        dependency-type: development
      production-dependencies:
        dependency-type: production
    open-pull-requests-limit: 2

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies
      - skip-changelog
    groups:
      actions:
        patterns: ["*"]
    ignore:
      - dependency-name: changesets/action
        versions: [">=2.0.0"]
    open-pull-requests-limit: 2
