version: "0.2"
language: en
words:
  - ACIP
  - astrojs
  - codemod
  - CodeLens
  - codicon
  - commitizen
  - commitlint
  - Consolas
  - dep
  - depbeacon
  - esbuild
  - GHSA
  - jsonc
  - keytar
  - knip
  - linecap
  - linejoin
  - npmjs
  - OpenVSX
  - osv
  - OVSX
  - OVSX_PAT
  - packument
  - prerelease
  - rollup
  - semver
  - Snyk
  - unrs
  - vite
  - vitest
  - vulns
  - vsc
  - vsce
  - VSIX
  - workerd
  - workspaces
  - santi020k
ignorePaths:
  - node_modules
  - dist
  - coverage
  - pnpm-lock.yaml
  - "*.vsix"
