version: "0.2"
language: en
words:
  - ACIP
  - axios
  - astrojs
  - clsx
  - codemod
  - CodeLens
  - codicon
  - cdylib
  - commitlint
  - commitprompt
  - Consolas
  - dasharray
  - dep
  - depbeacon
  - domexception
  - esbuild
  - expressjs
  - fflate
  - GHSA
  - Ghsas
  - jsonc
  - katex
  - keytar
  - knip
  - labelledby
  - linecap
  - linejoin
  - linkify
  - lates
  - lstrip
  - npmjs
  - noopener
  - noreferrer
  - OpenVSX
  - osv
  - OVSX
  - OVSX_PAT
  - packument
  - pathlib
  - prebuild
  - prerelease
  - rollup
  - rstrip
  - rustup
  - santi
  - Segoe
  - semver
  - Snyk
  - smol
  - tlsv
  - undici
  - unrs
  - unstub
  - vite
  - vitest
  - vulns
  - vsc
  - vsce
  - VSIX
  - wasip
  - whatwg
  - workerd
  - workspaces
  - worktree
  - santi020k
ignorePaths:
  - node_modules
  - dist
  - coverage
  - pnpm-lock.yaml
  - "*.vsix"
