packages:
  - "packages/*"

catalog:
  astro: ^7.0.0
  left-pad: 1.1.0
  typescript: ^6.0.3
  vitest: ^3.0.0

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
  conflicts_astro_h6_4_0:
    astro: ^6.4.0
  conflicts_typescript_h5_4_0:
    typescript: ^6.0.3

overrides:
  rollup: ^4.62.2
  vite: ^8.0.16

packageExtensions:
  left-pad@*:
    dependencies:
      debug: ^4.4.3
